#!/bin/bash
# JankyBorders. Restart with: brew services restart borders

options=(
        style=round
        active_color=0xffbd93f9
        inactive_color=0xff44475a
        width=8.0
        hidpi=on
        ax_focus=on
        blacklist="Hammerspoon"
)

borders "${options[@]}"
